repos:
  - repo: local
    hooks:
      - id: spotless-check
        name: Spotless Check
        language: system
        entry: ./gradlew spotlessCheck
        pass_filenames: false
        types: [java]
