spring:
  config:
    import:
      - classpath:storage.yml
      - classpath:security.yml
      - classpath:external.yml

management:
  endpoints:
    web:
      exposure:
        include: health

auth:
  bypass-login:
    phone: ${BYPASS_LOGIN_PHONE}
    code: ${BYPASS_LOGIN_CODE}
    name: ${BYPASS_LOGIN_NAME}
