sentry:
  dsn: ${DEV_SENTRY_DSN}
  environment: dev
  traces-sample-rate: 1.0
  send-default-pii: false
  enable-tracing: true
  logging:
    minimum-event-level: warn
    minimum-breadcrumb-level: info
