package org.sopt.makers.domain.playground.post;

public enum PostCategory {
  FREE,
  MEETING,
  PROMOTION,
  PROMOTION_EVENT,
  PROMOTION_PROJECT,
  PROMOTION_RECRUIT,
  PROMOTION_ETC,
  SOPTICLE,
  SOPTICLE_PLAN,
  SOPTICLE_DESIGN,
  SOPTICLE_SERVER,
  SOPTICLE_WEB,
  SOPTICLE_IOS,
  SOPTICLE_ANDROID,
  SOPTICLE_ETC
}
